title: Blog - teisyogun
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "https://teisyogun.oschina.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings add your name
author: Teisyogun

author-name: teisyogun
author-pic: leach-face.jpg
about-author: The expert in anything was once a beginner. Helen Hayes

#修改成你自己的
# Contact links
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的
email: 512357657@qq.com
phone: 15213096507
github: https://github.com/bushrose
jianshu: https://www.jianshu.com/u/3083cf528b0f
juejin: https://juejin.im/user/5adedb0ef265da0b7868271b
csdn: https://blog.csdn.net/qq_27066797



# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier: leach-chen
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier: 1ce8d80a5f6d373a46f4ceaf3dff8859

# Gitalk
gitalk: 
  enable: true    #用来做启用判断可以不用
  clientID: '27c38d4480505553d62d'    #上面生成的往这里怼
  clientSecret: '33be549572272c79d09d973bb56907d29d9c9dc1'   #同上
  repo: blog_comments    #仓库名称
  owner: bushrose    #github用户名
  admin: [bushrose]
  distractionFreeMode: true

# Declare license on posts
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/


# Tracker Google Analytics修改成你自己的
google-analysis: UA-113644888-1
baidu-analysis: 56385150d223d3a72bebe8a0d4a94e19

#youyan
youyan-id: 2157296

# Paginate
paginate: 18
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]


links:
  - name:         Home
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容


links1:
  - name:         所有
    url:          /
    type:         recent
    external:     false
  - name:         随笔
    url:          /blog/essays
    type:         essays
    external:     false
  - name:         Jekyll
    url:          /blog/jekyll
    type:         jekyll
    external:     false
  - name:         Android
    url:          /blog/android
    type:         androidoriginal
    external:     false
  - name:         逆向笔记
    url:          /blog/hacker
    type:         hacker
    external:     false
  - name:         Flutter
    url:          /blog/flutter
    type:         flutter
    external:     false
  - name:         FFmpeg
    url:          /blog/ffmpeg
    type:         ffmpeg
    external:     false
  - name:         OpenGL
    url:          /blog/opengl
    type:         opengl
    external:     false
  - name:         Python
    url:          /blog/python
    type:         python
    external:     false
  - name:         测试相关
    url:          /blog/abouttest
    type:         abouttest
    external:     false
  - name:         股票
    url:          /blog/stock
    type:         stock
    external:     false
  - name:         其它
    url:          /blog/other
    type:         other
    external:     false
  - name:         代码战争
    url:          /blog/codewar
    type:         codewar
    external:     false
blog_1:    recent
blog_2:    essays
blog_3:    jekyll
blog_4:    androidoriginal
blog_5:    abouttest
blog_6:    stock
blog_7:    other
blog_8:    python
blog_9:    flutter
blog_10:   ffmpeg
blog_11:   opengl
blog_12:   hacker
blog_13:   codewar
blog_14:
blog_15:
blog_16:


#permalink: /:year/:month/:day/:title.html

theme: jekyll-theme-leap-day
